### ISSUE TITLE
Старые фото

### ISSUE THREAD

**Issue by eastwing** [rgrdfo/rgr.core#7]
Необходимо восстановить доступ к ресурсам (в основном, фото объектов и людей) старого сайта.

**Comment by PKoroboff** [comment]
Я уже пробовал это сделать, тот человек, на чьем ресурсе они находились - избегает контактов. Скорее всего он убил все это, поэтому будем исходить из того, что есть. Нужно заново собирать эти данные, а лучше - дать людям возможность самим эти данные указать. То есть нужно писать интерфейс внутреннего кабинета, где они уже сами смогут указывать фото объектов, компаний, свои и т.д.

**Comment by eastwing** [comment]
Речь о том, чтобы работа со старыми и новыми файлами велась идентичным образом, т.е.,чтобы между ними просто не было разницы. Кроме того, многие старые файлы сохранились - например, твоё фото

**Comment by PKoroboff** [comment]
Старые фото уже не вернуть, с новыми конечно должно все работать. И будет работать одинаково. Свое фото я сам добавил заново, оно не сохранилось
